added packager and cleaned package.son
csus190teamtbd/SeniorProject pull request #62
Opened 2019-04-20 12:05 UTC by aryue123321

I have tested the windows package on windows 10.

2019-04-22 03:04 UTC, MatthewMerrill commented
testing on linux

2019-04-22 03:10 UTC, MatthewMerrill requested changes

2019-04-22 03:10 UTC, MatthewMerrill commented on package.json
> +  "description": "Statistical Analysis Vizualizions for Introtuctory Statistics",
```suggestion
  "description": "Statistical Analysis Visualizations for Introductory Statistics",
```

2019-04-22 03:10 UTC, MatthewMerrill commented on package.json
> +    "package-mac": "electron-packager . --overwrite --platform=darwin --arch=x64 --prune=true --out=dist",
I don't have a mac, can we test this on one? I can rent a laptop from the library tomorrow to test. Without knowing this library or having tried it yet, it seems strange that this one has no "savis" as an arg.

2019-04-22 03:14 UTC, MatthewMerrill commented
works on my machine :+1:

2019-04-24 09:38 UTC, merged

2019-04-24 09:39 UTC, aryue123321 commented on package.json
> +    "package-mac": "electron-packager . --overwrite --platform=darwin --arch=x64 --prune=true --out=dist",
yeah, i noticed that too.  Copied those from somewhere and wanna see what is the output on mac first